network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s0:
      dhcp4: no
      dhcp6: no
      mtu: 1466
  bridges:
    br0:
      interfaces: [enp0s0]
      dhcp4: no
      dhcp6: no
      addresses:
        - 10.10.0.11/24
      routes:
        - to: default
          via: 10.10.0.10
      nameservers:
        addresses: [140.112.30.21, 8.8.8.8]
      parameters:
        stp: true
      mtu: 1466
